# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
  branches:
    include:
    - main
  paths:
    include:
    - frontend/*
    - azure-pipelines-frontend.yml

pool:
  vmImage: ubuntu-latest

stages:
- stage: BuildPayrollFrontend
  displayName: 'Build'
  jobs:
  - job: build_test
    displayName: 'Build and test'
    steps:
    - task: NodeTool@0
      inputs:
        versionSpec: '10.x'

    - script: |
        npm install
        npm run-script
      displayName: 'npm install and build'
      workingDirectory: '$(Build.SourcesDirectory)/frontend'

    - task: CopyFiles@2
      inputs:
        Contents: 'node_modules/**' # Pull the build directory (React)
        TargetFolder: '$(Build.ArtifactStagingDirectory)'
