# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
  branches:
    include:
    - main
  paths:
    include:
    - frontend/*
    - azure-pipelines-frontend.yml

pool:
  vmImage: ubuntu-latest

stages:
- stage: BuildPayrollFrontend
  displayName: 'Build Frontend'
  jobs:
  - job: buildtest
    displayName: 'Build and test'
    steps:
    - task: NodeTool@0
      inputs:
        versionSpec: '10.x'

    - script: |
        npm install
        npm start
      displayName: 'npm install and build'
      workingDirectory: '$(Build.SourcesDirectory)/frontend'

# pipeline stage to build and push the backend container to a docker registry, authenticated through service connection 
- stage: PushFrontendContainerImage
  dependsOn:
  - BuildPayrollFrontend
  condition: succeeded('BuildPayrollFrontend')
  jobs:
  - job: PushFrontendImage
    displayName: Build and Push Frontend image to registry 

    steps:
      - task: Docker@2
        displayName: Build and Push 
        inputs:
          command: buildAndPush
          containerRegistry: 'lakpriyagk-docker-hub-service-connection'
          repository: 'lakpriyagk/contoso-payroll-frontend'
          tags: '$(Build.BuildId)'
