# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

variables:
  SERVICE_CONNECTION: lakpriyagk-docker-hub-service-connection

trigger:
  branches:
    include:
    - main
  paths:
    include:
    - full-app/*
    - azure-pipelines-full-app.yml

pool:
  vmImage: ubuntu-latest

stages:
# pipeline stage to compile backend code 
- stage: BuildPayrollApp
  jobs:
  - job: BuildPayrollApp
    displayName: Build Payroll with Maven
    steps:
      - task: Maven@3
        inputs:
          mavenPomFile: 'full-app/pom.xml'
          mavenOptions: '-Xmx3072m'
          javaHomeOption: 'JDKVersion'
          jdkVersionOption: '1.11'
          jdkArchitectureOption: 'x64'
          publishJUnitResults: true
          testResultsFiles: '**/surefire-reports/TEST-*.xml'
          goals: 'package'

# pipeline stage to build and push the backend container to a docker registry, authenticated through service connection 
# - stage: PushAppContainerImage
#   dependsOn:
#   - BuildPayrollApp
#   condition: succeeded('BuildPayrollApp')
#   jobs:
#   - job: PushAppImage
#     displayName: Build and Push container image to docker hub

#     steps:
#       - task: Docker@2
#         displayName: Build and Push 
#         inputs:
#           command: buildAndPush
#           containerRegistry: 'lakpriyagk-docker-hub-service-connection'
#           Dockerfile: full-app/Dockerfile
#           repository: $(DOCKER_REGISTORY)
#           tags: '$(Build.BuildId)'