# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

variables:
  SERVICE_CONNECTION: lakpriyagk-docker-hub-service-connection
  RESOURCEGROUP_NAME: 'lakolk-test-rg'
  LOCATION: 'westeurope'

trigger:
  branches:
    include:
    - main
  paths:
    include:
    - infrastucture/*
    - azure-pipelines-infra.yml

pool:
  vmImage: windows-latest

stages:
- stage: BuildPayrollInfrastructure 
  displayName: 'Build Payroll Infrastructure'
  jobs:
  - job: ResourceGroup
    displayName: 'Create Resource Group'
    steps:
    - task: AzureResourceGroupDeployment@2
      inputs:
        azureSubscription: 
        action: Create
        resourceGroupName: $(RESOURCEGROUP_NAME)
        location: $(LOCATION)
