# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

parameters:
- name: ResourceGroupName
  displayName: Resource Group Name
  type: string

variables:
  SERVICE_CONNECTION: lakpriyagk-arm-subscription-service-connection
  RESOURCEGROUP_NAME: 'lakolk-test-rg'
  LOCATION: 'westeurope'

trigger:
  branches:
    include:
    - main
  paths:
    include:
    - infrastucture/*
    - azure-pipelines-infra.yml

pool:
  vmImage: windows-latest

stages:
- stage: DeployPayrollBaseInfrastructure 
  displayName: 'Deploy Payroll BaseInfrastructure'
  jobs:
  - job: Deploy 
    displayName: 'Create Resource Group'
    steps:
    - checkout: self
    - task: AzureResourceGroupDeployment@2
        inputs:
          azureSubscription: $(SERVICE_CONNECTION)
          action: 'Create Or Update Resource Group'
          resourceGroupName: '${{ parameters.ResourceGroupName }}'
          location: $(LOCATION)
          deploymentMode: 'Incremental'
