# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

parameters:
- name: ResourceGroupName
  displayName: Resource Group Name
  type: string

variables:
  SERVICE_CONNECTION: lakpriyagk-arm-subscription-service-connection
  RESOURCEGROUP_NAME: '${{ parameters.ResourceGroupName }}'
  LOCATION: 'westeurope'
  APP_SERV_PLAN: 'payroll-app-serv-plan'

trigger:
  branches:
    include:
    - main
  paths:
    include:
    - infrastucture/*
    - azure-pipelines-infra.yml

pool:
  vmImage: windows-latest

stages:
- stage: DeployPayrollBaseInfrastructure 
  displayName: 'Deploy Payroll Base Infrastructure'
  jobs:
  - job: DeployAppServicePlan 
    displayName: 'Deploy AppService Plan'
    steps:
    - task: AzureResourceGroupDeployment@2
      inputs:
        azureSubscription: $(SERVICE_CONNECTION)
        action: 'Create Or Update Resource Group'
        resourceGroupName: '$(RESOURCEGROUP_NAME)'
        location: $(LOCATION)
        deploymentMode: 'Incremental'
        templateLocation : 'URL of the file'
        csmFileLink: 'https://raw.githubusercontent.com/lakpj/contoso-payroll/infra-pipeline/infrastucture/AppServicePlan/azuredeploy.json'
  - job: DeployWebappToServicePlan 
    displayName: 'Deploy Webapp To Application Service Plan'
    steps:
    - task: AzureCLI@2
      inputs:
        azureSubscription: $(SERVICE_CONNECTION)
        scriptType: ps
        scriptLocation: inlineScript
        workingDirectory: $(System.DefaultWorkingDirectory)/infrastructure
        inlineScript: |
          az webapp create --resource-group $(RESOURCEGROUP_NAME) \
          --plan myAppServicePlan --name $(APP_SERV_PLAN) \
          --multicontainer-config-type compose \
          --multicontainer-config-file docker-compose-payroll.yml
