# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

parameters:
- name: ResourceGroupName
  displayName: Resource Group Name
  type: string
- name: Region
  displayName: Azure region
  type: string

variables:
- group: ContosoPayroll
- name: RESOURCEGROUP_NAME
  value: '${{ parameters.ResourceGroupName }}'
- name: LOCATION
  value: '${{ parameters.Region }}'

trigger:
  branches:
    include:
    - main
  paths:
    include:
    - infrastucture/*
    - azure-pipelines-infra.yml

pool:
  vmImage: windows-latest

stages:
# - stage: DeployAppServicePlan
#   jobs:
#    - job: DeployAppServicePlan 
#      displayName: 'Deploy AppService Plan'
#      steps:
#      - task: AzureResourceGroupDeployment@2
#        inputs:
#          azureSubscription: $(ARM_SERVICE_CONNECTION)
#          action: 'Create Or Update Resource Group'
#          resourceGroupName: '$(RESOURCEGROUP_NAME)'
#          location: $(LOCATION)
#          deploymentMode: 'Incremental'
#          templateLocation : 'URL of the file'
#          csmFileLink: 'https://raw.githubusercontent.com/lakpj/contoso-payroll/deploy-webapp/infrastucture/AppServicePlan/azuredeploy.json'
#          csmParametersFileLink: 'https://raw.githubusercontent.com/lakpj/contoso-payroll/deploy-webapp/infrastucture/AppServicePlan/azuredeploy.parameters.json'
#          deploymentName: 'DeployAppServicePlan'
- stage: DeployDatabase 
  jobs:  
  - job: DeployDatabase 
    displayName: 'Deploy MySql database'
    steps:    
    - task: AzureResourceManagerTemplateDeployment@3
      inputs:
        azureResourceManagerConnection: $(ARM_SERVICE_CONNECTION)
        action: 'Create Or Update Resource Group'
        resourceGroupName: '$(RESOURCEGROUP_NAME)'
        location: $(LOCATION)
        deploymentMode: 'Incremental'
        templateLocation : 'URL of the file'
        csmFileLink: 'https://raw.githubusercontent.com/lakpj/contoso-payroll/deploy-webapp/infrastucture/MySqldb/azuredeploy.json'
        csmParametersFileLink: 'https://raw.githubusercontent.com/lakpj/contoso-payroll/deploy-webapp/infrastucture/MySqldb/azuredeploy.parameters.json'
        deploymentScope: 'Resource Group'    
        deploymentName: 'DeployDatabase'
# - stage: DeployWebappToServicePlan 
#   dependsOn:
#   - DeployAppServicePlan
#   condition: succeeded('DeployAppServicePlan')
#   jobs:  
#   - job: DeployWebapp 
#     displayName: 'Deploy Webapp To Application Service Plan'
#     steps:    
#     - task: AzureResourceManagerTemplateDeployment@3
#       inputs:
#         azureResourceManagerConnection: $(ARM_SERVICE_CONNECTION)
#         action: 'Create Or Update Resource Group'
#         resourceGroupName: '$(RESOURCEGROUP_NAME)'
#         location: $(LOCATION)
#         deploymentMode: 'Incremental'
#         templateLocation : 'URL of the file'
#         csmFileLink: 'https://raw.githubusercontent.com/lakpj/contoso-payroll/deploy-webapp/infrastucture/Webapp/azuredeploy.json'
#         csmParametersFileLink: 'https://raw.githubusercontent.com/lakpj/contoso-payroll/deploy-webapp/infrastucture/Webapp/azuredeploy.parameters.json'
#         deploymentScope: 'Resource Group'    
#         deploymentName: 'DeployWebapp'  
# - stage: EnableMonitoringToWebapp 
#   dependsOn:
#   - DeployWebappToServicePlan
#   condition: succeeded('DeployWebappToServicePlan')
#   jobs:
#   - job: EnableMonitoring 
#     displayName: 'Enable Monitoring To Webapp'
#     steps:
#     - task: AzureResourceManagerTemplateDeployment@3
#       inputs:
#         azureResourceManagerConnection: $(ARM_SERVICE_CONNECTION)
#         action: 'Create Or Update Resource Group'
#         resourceGroupName: '$(RESOURCEGROUP_NAME)'
#         location: $(LOCATION)
#         deploymentMode: 'Incremental'
#         templateLocation : 'URL of the file'
#         csmFileLink: 'https://raw.githubusercontent.com/lakpj/contoso-payroll/deploy-webapp/infrastucture/AppMonitoring/azuredeploy.json'
#         csmParametersFileLink: 'https://raw.githubusercontent.com/lakpj/contoso-payroll/deploy-webapp/infrastucture/AppMonitoring/azuredeploy.parameters.json'
#         deploymentScope: 'Resource Group'    
#         deploymentName: 'DeployMonitoring'