version: "3.3"
services:
  backend:
    image: "lakpriyagk/contoso-payroll-backend:34"
    container_name: "backend"
    ports:
      - "8080:8080"
    restart: always

  frontend:
    image: "lakpriyagk/contoso-payroll-frontend:56"
    container_name: "frontend"
    depends_on:
      - backend