version: "3"
services:
  backend:
    image: "lakpriyagk/contoso-payroll-backend"
    container_name: "backend"
    ports:
      - "8080:8080"

  frontend:
    image: "lakpriyagk/contoso-payroll-frontend"
    container_name: "frontend"
    ports:
      - "80:80"
    depends_on:
      - backend