version: "3"
services:
  backend:
    image: "contoso-payroll-backend:34"
    container_name: "backend"
    ports:
      - "8080:8080"

  frontend:
    image: "contoso-payroll-frontend:56"
    container_name: "frontend"
    ports:
      - "80:80"
    depends_on:
      - backend